apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mymicro
data:
  USERS_SERVICE_URL: "http://api-users:8080"
  ORDERS_SERVICE_URL: "http://api-orders:8080"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "appdb"

