apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-orders
  namespace: mymicro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-orders
  template:
    metadata:
      labels:
        app: api-orders
    spec:
      containers:
        - name: api-orders
          image: jaydaniel10/api-orders:1.0.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api-orders
  namespace: mymicro
spec:
  selector:
    app: api-orders
  ports:
    - port: 8080
      targetPort: 8080

